### ISSUE TITLE
Bob: Environment variable PATH is broken in Neovim when launched in Tmux session

### ISSUE THREAD

**Issue by Hubro** [tirimia/neovim-nix#30]
My nvim just exploded violently today. It turns out it was because I launched it inside a Tmux session. After some experimenting, it seems like any nvim instance installed through bob (from this flake) when launched in a Tmux session has its `PATH` environment variable mysteriously set to:

```
nixpkgxpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels
```

(Output by `:lua print(vim.env.PATH)`)

Which makes all my plugins explode for various reasons, such as not finding Git.

Running nvim without bob from this flake works fine, e.g.:

```
$ nix run github:tirimia/neovim-nix#nightly
```

---

EDIT: I temporarily resolved this by installing Neovim nightly system-wide from your flake. However, as soon as I proceeded to work on my project, I realized NodeJS installed through `fnm` has the exact same problem:

```
$ node
Welcome to Node.js v20.11.0.
Type ".help" for more information.
> process.env.PATH
'nixpkgxpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels'
```

And this only happens when I launch it from a tmux session... What the hell is going on :dizzy_face::dizzy:

Ref: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/tools/fnm/default.nix

**Comment by tirimia** [comment]
From what I have found online, it might be because `tmux` starts login shells, not "interactive" ones. Try changing your tmux config like [this](https://wiki.archlinux.org/title/tmux#Start_a_non-login_shell), hopefully that will cause your `$PATH` to be loaded correctly 😸 

Thank you, by the way, for being an active user and opening issues, it really helps ❤️

**Comment by Hubro** [comment]
> From what I have found online, it might be because `tmux` starts login shells, not "interactive" ones. Try changing your tmux config like [this](https://wiki.archlinux.org/title/tmux#Start_a_non-login_shell), hopefully that will cause your `$PATH` to be loaded correctly 😸

That doesn't seem to be the case, changing the default command as described didn't do anything. Launching `tmux kill-server; tmux new-session zsh --no-login` also still has the same issue.

However, I did just notice that the same issue doesn't happen with bash, which hopefully helps narrow it down:

```
[tomas@cross:~]$ node -e "console.log(process.env.PATH)"
/home/tomas/.local/share/bob/nvim-bin:/home/tomas/bin:/run/user/1000/fnm_multishells/1467681_1706472471688/bin:/home/tomas/.local/share/bob/nvim-bin:/home/tomas/bin:/nix/store/zvdr7sc4b5jb7ixpm1af05zm4ycsfvss-kitty-0.32.0/bin:/nix/store/6kwdwy2bafpgvcl3j3mimmyivkpj25rf-imagemagick-7.1.1-25/bin:/nix/store/41iqz1dhnzww1npdcqw52cz3yhsi9n7g-ncurses-6.4-dev/bin:/run/wrappers/bin:/home/tomas/.nix-profile/bin:/nix/profile/bin:/home/tomas/.local/state/nix/profile/bin:/etc/profiles/per-user/tomas/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/home/tomas/.zsh/plugins/zsh-vi-mode:/nix/store/2cvpxhj5gifb9g8hd0w6zbnnqmhl86vk-binutils-wrapper-2.40/bin:/nix/store/n9ilxxh5w0q3xj824kclsw6m4hkdph2z-pciutils-3.10.0/bin
```

Unfortunately I have absolutely no clue which mechanism can cause processes launched from `zsh` under `tmux` to have a borked PATH, but not `zsh` itself...

> Thank you, by the way, for being an active user and opening issues, it really helps ❤️

The pleasure is all mine :smile:

**Comment by Hubro** [comment]
So, how is this even technically possible:

Any binary installed through a version manager (bob, fnm) has its PATH variable mangled, but only if launched from `zsh` inside a `tmux` session.

I have no clue what could even possibly cause this :laughing:

```
$ PATH="/run/user/1000/fnm_multishells/1478854_1706472798854/bin" node -e "console.log(process.env.PATH)"
nixpkgxpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels
```

But I assume it must have something to do with whatever patching is done to make these binaries run on NixOS.

**Comment by tirimia** [comment]
Have you tested it with a stock `zsh` configuration and if that ends up working, what `nix` or `$PATH` related configs do you have in your `.zshrc` or any of the [other files](https://zsh.sourceforge.io/Doc/Release/Files.html) `zsh` loads ?

**Comment by Hubro** [comment]
Running zsh without any userrc files (`zsh -f`) still produces the same problem:

```
cross% node -e "console.log(process.env.PATH)"
nixpkgxpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels
```

Even if I completely clear my environment first:

```
tmux new-session env -i zsh -f
```

```
cross% /run/user/1000/fnm_multishells/1577981_1706475935717/bin/node -e "console.log(process.env.PATH)"
nixpkgxpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels
```

Better yet, launching node from bash inside zsh inside tmux doesn't cause the same problem:

![image](https://github.com/tirimia/neovim-nix/assets/597206/7a7234cc-7ff8-476e-ae97-31aea8085bff)

![confused](https://media.tenor.com/eRjjRricmzMAAAAM/krule-john-c-reilly.gif)

**Comment by Hubro** [comment]
Hold on, here's some more confusion:

- When inside `tmux new-session bash`, both `bash -c ...` and `zsh -c ...` produce the correct behavior
- When inside `tmux new-session zsh`, then `bash -c ...` produces the correct behavior, but `zsh -c ...` is broken

![screenshot 1](https://github.com/tirimia/neovim-nix/assets/597206/1fb82fd3-8e7b-4bb5-9f18-92dce48863c8)

![screenshot 1](https://github.com/tirimia/neovim-nix/assets/597206/9ddafa5f-94dc-4c8f-ae55-ae81e6b35fd1)

**Comment by Hubro** [comment]
Oh, I just tried using zsh wrapped inside bash as my tmux command:

```
tmux new-session bash -c "zsh -i"
```

And that works around the issue somehow :man_shrugging:

![image](https://github.com/tirimia/neovim-nix/assets/597206/b9e63007-fc1e-49ec-a5b6-0a45aa0d46bc)

I exported my environment variables (`env | sort > ...`) inside `tmux new-session zsh` vs `tmux new-session bash -c "zsh -i"` and diffed them. They are completely identical. Whatever the problem is, it doesn't have anything to do with environment variables.

---

So in any case, this snippet effectively works around this bug with no side effects that I've discovered thus far:

```nix
{
  programs.tmux.extraConfig = ''
    # Always use bash as the outermost entrypoint for tmux, otherwise
    # strange and inexplicable bugs occur.
    #
    # ref: https://github.com/tirimia/neovim-nix/issues/30
  
    set -g default-command "bash -c ''${SHELL}"
  ''
}
```

So this issue is no longer very pressing for me :smile:

**Comment by Hubro** [comment]
Sorry for the noise, but this issue just came crashing back :smile:

Now my editor explodes violently when I run `git commit` in the terminal, which I do rarely. (I primarily use fugitive within Neovim.)

In other words, when the `git` command launches `nvim` (installed through `bob`) directly, `nvim`'s PATH gets messed up:

```
:lua print(os.getenv("PATH"))
nixpkgxpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels
```

And I just realized what this value is, it's my `NIX_PATH`!

```
$ echo $NIX_PATH
nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels
```

So for some reason, when `nvim` (installed through `bob`) is launched from any binary *except* bash, its `PATH` gets overwritten by `NIX_PATH`.

As expected, when I run `EDITOR="bash -c nvim" git commit` then the problem goes away.

Now I'm almost certain there's a bug somewhere where PATH and NIX_PATH is accidentally mixed up, though I'm not sure if it's in nixpkgs or neovim-nix.

**Comment by Hubro** [comment]
I still have no idea what causes this, but I thought I'd share the workaround I settled on. I made a wrapper for Neovim:

**`$HOME/bin/nvim`:**

```bash
#!/usr/bin/env bash
#
# Wrapper that executes nvim through bash, which works around a bizarre
# inexplicable bug where nvim installed through bob has its "PATH" variable
# mangled *unless* it's executed from Bash.
#

SELF="${BASH_SOURCE[0]}"
IFS=$'\n' NVIMS=($(which -a nvim))

# Execute the first nvim found (excluding this script)
for NVIM in "${NVIMS[@]}"; do
	if [[ "$(realpath "$NVIM")" == "$(realpath "$SELF")" ]]; then
		continue
	fi

	exec "$NVIM" "$@"
done
```

It just makes sure nvim is always executed through bash. This is simpler than addressing the issue from tmux, git, neovide etc.
